version: '3.5'

services:
  nginx-php-fpm:
    image: webdevops/php-nginx:7.3
    restart: always
    container_name: nginx-php
    ports:
      - 80:80
    networks:
      custom_network:
        ipv4_address: 172.30.0.10
    environment:
      - WEB_DOCUMENT_ROOT=/app
      - WEB_DOCUMENT_INDEX=index.php
    volumes:
      - ./src/index.php:/app/index.php

  db:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3306:3306
    networks:
      custom_network:
        ipv4_address: 172.30.0.11
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    volumes:
      - ./data:/var/lib/mysql
      - ./src/database:/docker-entrypoint-initdb.d

networks:
  custom_network:
    name: custom_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
